### ISSUE TITLE
[FR] Add Statusbar Menu Icon to turn on or off selected plugins like in Plugin Groups

### ISSUE THREAD

**Issue by ianTevesAcc** [alangrainger/obsidian-lazy-plugins#10]
In the Obsidian Plugin Groups plugin, there used to be a really handy feature that let you toggle a plugin or a whole group of plugins on or off using an icon in the status bar.

![image](https://github.com/user-attachments/assets/c46c0c2e-74d6-4c06-a9de-afd4ef9cc499)

Unfortunately, since the OB Plugin Groups is no longer being maintained, this feature isn’t working anymore. I have certain plugins that I only need to activate based on my current needs, and having this toggle feature would really help!

**Comment by alangrainger** [comment]
Thanks - it's a good suggestion, but I want to keep this plugin as lean as possible so that it itself doesn't delay Obsidian startup any more than it has to.

I can suggest a VERY easy solution which you can immediately implement:

Create two Templater templates or CustomJS scripts, and assign them to hotkeys.

Inside the template/script, do this to enable/disable your plugins:

```javascript
// Enable the Dataview plugin
app.plugins.enablePlugin('dataview')

// Disable the Dataview plugin
app.plugins.disablePlugin('dataview')
```

And just use the IDs for the specific plugins that you want rather than `dataview`.

**Comment by ianTevesAcc** [comment]
@alangrainger 
I NEVER EVEN KNEW THIS WAS POSSIBLE! THANKS! ^^

**Comment by alangrainger** [comment]
You're welcome. For your reference there is basically nothing that a plugin can do that you can't do just with a Templater template. So don't feel limited, you can customize everything about your Obsidian experience and you don't need plugins to do it.
